In [1]:
import pandas as pd
import os

datasets = {}

data_path = "data/raw"

for file_name in os.listdir(data_path):
    if file_name.endswith(".csv"):
        file_path = os.path.join(data_path, file_name)
        
        dataset_name = file_name.replace(".csv", "")
        datasets[dataset_name] = pd.read_csv(file_path)

print("Datasets loaded:", len(datasets))
print("Dataset names:", list(datasets.keys()))

Datasets loaded: 18
Dataset names: ['accounts', 'account_status_history', 'agents', 'agent_sessions', 'borrowers', 'calls', 'call_attempts', 'call_dispositions', 'campaigns', 'complaints', 'daily_targeting', 'data_dictionary', 'field_visits', 'payments', 'promises_to_pay', 'sms_events', 'vendor_telephony', 'whatsapp_events']

In [2]:
schema_summary = []

for dataset_name, df in datasets.items():
    schema_summary.append({
        "dataset": dataset_name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": ", ".join(df.columns.astype(str).tolist())
    })

schema_summary_df = pd.DataFrame(schema_summary)

schema_summary_df

,dataset,rows,columns,column_names
0,accounts,30000,11,"account_id, borrower_id, loan_type, principal_..."
1,account_status_history,60000,8,"history_id, account_id, borrower_id, event_at,..."
2,agents,30000,8,"agent_id, employee_code, agent_name, vendor_id..."
3,agent_sessions,15000,7,"session_id, agent_id, login_at, channel, devic..."
4,borrowers,30600,8,"borrower_id, name, phone, email, city, created..."
5,calls,91350,11,"call_id, account_id, borrower_id, event_at, ag..."
6,call_attempts,120000,9,"attempt_id, account_id, borrower_id, event_at,..."
7,call_dispositions,35000,8,"disposition_id, account_id, borrower_id, event..."
8,campaigns,120,7,"campaign_id, campaign_name, channel, strategy_..."
9,complaints,8000,9,"complaint_id, account_id, borrower_id, event_a..."
10,daily_targeting,45000,7,"target_id, account_id, campaign_id, target_dat..."
11,data_dictionary,143,3,"dataset, column, dtype"
12,field_visits,25000,10,"visit_id, account_id, borrower_id, event_at, a..."
13,payments,25500,9,"payment_id, account_id, borrower_id, event_at,..."
14,promises_to_pay,18000,9,"ptp_id, account_id, borrower_id, event_at, age..."
15,sms_events,45000,8,"sms_event_id, account_id, borrower_id, event_a..."
16,vendor_telephony,15,6,"vendor_id, vendor_name, vendor_account_id, tim..."
17,whatsapp_events,60600,8,"whatsapp_event_id, account_id, borrower_id, ev..."

In [3]:
schema_summary = []

for dataset_name, df in datasets.items():
    schema_summary.append({
        "dataset": dataset_name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": ", ".join(df.columns.tolist())
    })

schema_summary_df = pd.DataFrame(schema_summary)

schema_summary_df

,dataset,rows,columns,column_names
0,accounts,30000,11,"account_id, borrower_id, loan_type, principal_..."
1,account_status_history,60000,8,"history_id, account_id, borrower_id, event_at,..."
2,agents,30000,8,"agent_id, employee_code, agent_name, vendor_id..."
3,agent_sessions,15000,7,"session_id, agent_id, login_at, channel, devic..."
4,borrowers,30600,8,"borrower_id, name, phone, email, city, created..."
5,calls,91350,11,"call_id, account_id, borrower_id, event_at, ag..."
6,call_attempts,120000,9,"attempt_id, account_id, borrower_id, event_at,..."
7,call_dispositions,35000,8,"disposition_id, account_id, borrower_id, event..."
8,campaigns,120,7,"campaign_id, campaign_name, channel, strategy_..."
9,complaints,8000,9,"complaint_id, account_id, borrower_id, event_a..."
10,daily_targeting,45000,7,"target_id, account_id, campaign_id, target_dat..."
11,data_dictionary,143,3,"dataset, column, dtype"
12,field_visits,25000,10,"visit_id, account_id, borrower_id, event_at, a..."
13,payments,25500,9,"payment_id, account_id, borrower_id, event_at,..."
14,promises_to_pay,18000,9,"ptp_id, account_id, borrower_id, event_at, age..."
15,sms_events,45000,8,"sms_event_id, account_id, borrower_id, event_a..."
16,vendor_telephony,15,6,"vendor_id, vendor_name, vendor_account_id, tim..."
17,whatsapp_events,60600,8,"whatsapp_event_id, account_id, borrower_id, ev..."

In [4]:
os.makedirs("output/analysis", exist_ok=True)

schema_summary_df.to_csv(
    "output/analysis/schema_summary.csv",
    index=False
)

print("Schema summary saved successfully!")

Schema summary saved successfully!

In [5]:
data_types_summary = []

for dataset_name, df in datasets.items():
    
    for column in df.columns:
        data_types_summary.append({
            "dataset": dataset_name,
            "column": column,
            "data_type": str(df[column].dtype),
            "non_null_count": df[column].notna().sum(),
            "null_count": df[column].isna().sum(),
            "unique_values": df[column].nunique()
        })

data_types_df = pd.DataFrame(data_types_summary)

data_types_df.head(20)

,dataset,column,data_type,non_null_count,null_count,unique_values
0,accounts,account_id,str,30000,0,30000
1,accounts,borrower_id,str,29545,455,10943
2,accounts,loan_type,str,30000,0,5
3,accounts,principal_amount,float64,30000,0,29996
4,accounts,outstanding_amount,float64,30000,0,29994
5,accounts,dpd,int64,30000,0,11
6,accounts,risk_segment,str,30000,0,4
7,accounts,status,str,30000,0,4
8,accounts,opened_at,str,30000,0,29993
9,accounts,timezone,str,30000,0,3
10,accounts,schema_version,str,30000,0,3
11,account_status_history,history_id,str,60000,0,60000
12,account_status_history,account_id,str,60000,0,25999
13,account_status_history,borrower_id,str,60000,0,11916
14,account_status_history,event_at,str,60000,0,59898
15,account_status_history,status,str,60000,0,7
16,account_status_history,changed_by,str,60000,0,101
17,account_status_history,source,str,60000,0,5
18,account_status_history,recorded_at,str,60000,0,59906
19,agents,agent_id,str,30000,0,1000

In [6]:
data_types_summary = []

for dataset_name, df in datasets.items():
    
    for column in df.columns:
        data_types_summary.append({
            "dataset": dataset_name,
            "column": column,
            "data_type": str(df[column].dtype),
            "non_null_count": df[column].notna().sum(),
            "null_count": df[column].isna().sum(),
            "unique_values": df[column].nunique()
        })

data_types_df = pd.DataFrame(data_types_summary)

data_types_df.head(20)

,dataset,column,data_type,non_null_count,null_count,unique_values
0,accounts,account_id,str,30000,0,30000
1,accounts,borrower_id,str,29545,455,10943
2,accounts,loan_type,str,30000,0,5
3,accounts,principal_amount,float64,30000,0,29996
4,accounts,outstanding_amount,float64,30000,0,29994
5,accounts,dpd,int64,30000,0,11
6,accounts,risk_segment,str,30000,0,4
7,accounts,status,str,30000,0,4
8,accounts,opened_at,str,30000,0,29993
9,accounts,timezone,str,30000,0,3
10,accounts,schema_version,str,30000,0,3
11,account_status_history,history_id,str,60000,0,60000
12,account_status_history,account_id,str,60000,0,25999
13,account_status_history,borrower_id,str,60000,0,11916
14,account_status_history,event_at,str,60000,0,59898
15,account_status_history,status,str,60000,0,7
16,account_status_history,changed_by,str,60000,0,101
17,account_status_history,source,str,60000,0,5
18,account_status_history,recorded_at,str,60000,0,59906
19,agents,agent_id,str,30000,0,1000

In [7]:
data_types_df.to_csv(
    "output/analysis/data_types_summary.csv",
    index=False
)

print("Data types summary saved successfully!")

Data types summary saved successfully!

In [8]:
numerical_columns_summary = []

for dataset_name, df in datasets.items():
    
    numerical_columns = df.select_dtypes(
        include=["int64", "float64", "int32", "float32"]
    ).columns.tolist()
    
    numerical_columns_summary.append({
        "dataset": dataset_name,
        "numerical_columns": len(numerical_columns),
        "column_names": ", ".join(numerical_columns)
    })

numerical_columns_df = pd.DataFrame(
    numerical_columns_summary
)

numerical_columns_df

,dataset,numerical_columns,column_names
0,accounts,3,"principal_amount, outstanding_amount, dpd"
1,account_status_history,0,
2,agents,0,
3,agent_sessions,0,
4,borrowers,1,phone
5,calls,1,duration_sec
6,call_attempts,1,attempt_no
7,call_dispositions,0,
8,campaigns,0,
9,complaints,0,
10,daily_targeting,1,priority
11,data_dictionary,0,
12,field_visits,2,"latitude, longitude"
13,payments,1,amount
14,promises_to_pay,1,promised_amount
15,sms_events,0,
16,vendor_telephony,0,
17,whatsapp_events,0,

In [9]:
numerical_columns_df.to_csv(
    "output/analysis/numerical_columns_summary.csv",
    index=False
)

print("Numerical columns summary saved successfully!")

Numerical columns summary saved successfully!

In [10]:
categorical_columns_summary = []

for dataset_name, df in datasets.items():
    
    categorical_columns = df.select_dtypes(
        include=["object", "category", "bool"]
    ).columns.tolist()
    
    categorical_columns_summary.append({
        "dataset": dataset_name,
        "categorical_columns": len(categorical_columns),
        "column_names": ", ".join(categorical_columns)
    })

categorical_columns_df = pd.DataFrame(
    categorical_columns_summary
)

categorical_columns_df

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\200483350.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

,dataset,categorical_columns,column_names
0,accounts,8,"account_id, borrower_id, loan_type, risk_segme..."
1,account_status_history,8,"history_id, account_id, borrower_id, event_at,..."
2,agents,8,"agent_id, employee_code, agent_name, vendor_id..."
3,agent_sessions,7,"session_id, agent_id, login_at, channel, devic..."
4,borrowers,7,"borrower_id, name, email, city, created_at, up..."
5,calls,10,"call_id, account_id, borrower_id, event_at, ag..."
6,call_attempts,8,"attempt_id, account_id, borrower_id, event_at,..."
7,call_dispositions,8,"disposition_id, account_id, borrower_id, event..."
8,campaigns,7,"campaign_id, campaign_name, channel, strategy_..."
9,complaints,9,"complaint_id, account_id, borrower_id, event_a..."
10,daily_targeting,6,"target_id, account_id, campaign_id, target_dat..."
11,data_dictionary,3,"dataset, column, dtype"
12,field_visits,8,"visit_id, account_id, borrower_id, event_at, a..."
13,payments,8,"payment_id, account_id, borrower_id, event_at,..."
14,promises_to_pay,8,"ptp_id, account_id, borrower_id, event_at, age..."
15,sms_events,8,"sms_event_id, account_id, borrower_id, event_a..."
16,vendor_telephony,6,"vendor_id, vendor_name, vendor_account_id, tim..."
17,whatsapp_events,8,"whatsapp_event_id, account_id, borrower_id, ev..."

In [11]:
categorical_columns_df.to_csv(
    "output/analysis/categorical_columns_summary.csv",
    index=False
)

print("Categorical columns summary saved successfully!")

Categorical columns summary saved successfully!

In [12]:
missing_values_analysis = []

for dataset_name, df in datasets.items():
    
    missing_count = df.isna().sum().sum()
    
    missing_values_analysis.append({
        "dataset": dataset_name,
        "total_missing_values": missing_count,
        "missing_percentage": round(
            (missing_count / (df.shape[0] * df.shape[1])) * 100,
            2
        )
    })

missing_values_df = pd.DataFrame(
    missing_values_analysis
).sort_values(
    by="total_missing_values",
    ascending=False
).reset_index(drop=True)

missing_values_df

                   dataset  total_missing_values  missing_percentage
0            call_attempts                  2400                0.22
1                    calls                  1827                0.18
2                borrowers                  1509                0.62
3                 accounts                   455                0.14
4                 payments                   382                0.17
5             field_visits                   250                0.10
6   account_status_history                     0                0.00
7        call_dispositions                     0                0.00
8                   agents                     0                0.00
9           agent_sessions                     0                0.00
10              complaints                     0                0.00
11               campaigns                     0                0.00
12         data_dictionary                     0                0.00
13         daily_targeting                     0                0.00
14         promises_to_pay                     0                0.00
15              sms_events                     0                0.00
16        vendor_telephony                     0                0.00
17         whatsapp_events                     0                0.00

In [13]:
missing_values_df.to_csv(
    "output/analysis/missing_values_analysis.csv",
    index=False
)

print("Missing values analysis saved successfully!")

Missing values analysis saved successfully!

In [14]:
dataset_overview = []

for dataset_name, df in datasets.items():
    
    dataset_overview.append({
        "dataset": dataset_name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "total_cells": df.shape[0] * df.shape[1],
        "missing_values": df.isna().sum().sum(),
        "duplicate_rows": df.duplicated().sum()
    })

dataset_overview_df = pd.DataFrame(dataset_overview)

dataset_overview_df

,dataset,rows,columns,total_cells,missing_values,duplicate_rows
0,accounts,30000,11,330000,455,0
1,account_status_history,60000,8,480000,0,0
2,agents,30000,8,240000,0,0
3,agent_sessions,15000,7,105000,0,0
4,borrowers,30600,8,244800,1509,600
5,calls,91350,11,1004850,1827,1271
6,call_attempts,120000,9,1080000,2400,0
7,call_dispositions,35000,8,280000,0,0
8,campaigns,120,7,840,0,0
9,complaints,8000,9,72000,0,0
10,daily_targeting,45000,7,315000,0,0
11,data_dictionary,143,3,429,0,0
12,field_visits,25000,10,250000,250,0
13,payments,25500,9,229500,382,486
14,promises_to_pay,18000,9,162000,0,0
15,sms_events,45000,8,360000,0,0
16,vendor_telephony,15,6,90,0,0
17,whatsapp_events,60600,8,484800,0,600

In [15]:
dataset_overview_df.to_csv(
    "output/analysis/dataset_overview.csv",
    index=False
)

print("Final dataset overview saved successfully!")

Final dataset overview saved successfully!